### ISSUE TITLE
Example workflow fails without initialization if external modules present

### ISSUE THREAD

**Issue by timmeinerzhagen** [aquasecurity/tfsec-sarif-action#15]
The example workflow shown in this repository fails if you add it to a repository as is, if there are external modules present. This includes modules from the public registry e.g. `terraform-aws-modules/acm/aws` or any other modules. 

Since this standard workflow is recommended by GitHub via the `add code scanning tool` wizard in a repository, it would make sense to have a default workflows that doesn't fail in many cases.

Adding a step with `- run: terraform plan` before calling the `tfsec/tfsec-sarif-action` would already make it much more resilient (even though private registries / additional config would still not be present).

**Comment by robert-hill** [comment]
I agree. This would be much more valuable if it were able to perform an `init` in the invocation.

**Comment by owenrumney** [comment]
We can't run an init for you because we don't know which version of terraform you're running. I would suggest adding a step in your action workflow to do an init for the appropriate terraform version and then run the sarif action
